import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Nav from "@/components/Shared/Nav/Nav";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NextUIProvider>
            <Nav />
            <div>{children}</div>
            <Footer />
          </NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
